#!/usr/bin/python -tt
# -*- coding: utf-8 -*-

#DASR - Examen final
#Autor: David Rozas (drozas)

import os.path
import sys
import commands
import os
import shutil

def check_params():

	if (len(sys.argv)>=1):
		return 0
	else:
		return -1

if __name__ == '__main__':
	
	state = check_params()
	
	if (state == 0):
		print "ok"
	else:
		sys.stderr.write("Uso: ./pon_extension.py grupo directorio [-n]")

	
			
	sys.exit(state)
